version: '3'
volumes:
  tmp-vendor:
  tmp-node_modules:
services:
  api:
    image: ruby:2.7.6
    working_dir: /api
    volumes:
      - ./api:/api
    command: >
      bash -c "apt-get update &&
      bundle config set path 'vendor/bundle' &&
      bundle install &&
      bundle exec jets s --host=0.0.0.0"
    ports:
      - 8888:8888
    environment:
      RAILS_ENV: development
      DB_PASS: password
      DB_HOST: db
    depends_on:
      - db
  html:
    image: node:14
    working_dir: /html
    volumes:
      - ./html:/html
    ports:
      - 3000:3000
    command: "while :; do sleep 10; done"
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static/public:/public
    ports:
      - 8080:80
    depends_on:
      - api
      - html
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./.mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  memcached:
    image: memcached
